version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: urlshortlink-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: urlshortlink
      POSTGRES_USER: urluser
      POSTGRES_PASSWORD: urlpass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
